### PR TITLE
Added Edinburgh LC workshop 2018-05-14-edinburgh to the list of past …

### PR DESCRIPTION
**Pull request by anenadic**
…workshops

### CODE REVIEW

**Comment by fmichonneau** [comment]
hi @anenadic these files are generated automatically from AMY. It's best to make sure that the workshop is made public in AMY and it will appear in the feed, otherwise this edit will be overwritten.

**Comment by jezcope** [comment]
@fmichonneau has the work to enable this actually been done yet? When I set this up it was designed to mimic the output data from AMY in preparation but actually required manual updates.

**Comment by anenadic** [comment]
Hi, I was convinced it was done automatically by pulling from AMY but was confused about the missing Edinburg workshop. Someone from Edinburgh poked me about it so I thought I'd update it manually, as it looked like the updates were actually done manually - hence the PR. You can disregard it if it will all be done automatically in the future.

**Comment by anenadic** [comment]
Just closed it by mistake and reopened it.

**Comment by jezcope** [comment]
OK, well as a start I've opened #45 to track this. In the meantime we probably want to merge this PR so that the Edinburgh workshop appears.

**Comment by weaverbel** [comment]
We are still doing this manually @fmichonneau so @anenadic was right to do it this way. @libcce and I can manage PRs to this repo.

**Comment by libcce** [comment]
I've left an update here here https://github.com/LibraryCarpentry/new-website/issues/45

**Comment by anenadic** [comment]
Thanks everyone!

**Pull request merged**
