### PR TITLE
Create 2018-06-26-library-carpentry-inst-training.md

### PR DESCRIPTION
**Pull request by weaverbel**
draft blog post ready to go

### CODE REVIEW

**Comment by weaverbel** [comment]
Ready @libcce @tracykteal ?

**Comment by tracykteal** [comment]
I've made comments in the Google doc. @libcce will incorporate and update the PR

**Comment by weaverbel** [comment]
Ok, no problems. @libcce please ping me if you have any issues updating.

**Comment by libcce** [comment]
@weaverbel done!

**Pull request merged**
