### PR TITLE
Add workshop: 2018-09-25 Uni Bergen, Norway

### PR DESCRIPTION
**Pull request by danmichaelo**
Or perhaps this is generated from somewhere else?

### CODE REVIEW

**Comment by weaverbel** [comment]
Hi @danmichaelo We might generate this a different way in future but for now it is done the way you have done it. Merging it now - thanks !

**Comment by danmichaelo** [comment]
Thanks! Good you spotted the extra comma :)

**Comment by weaverbel** [comment]
The page kept failing to build @danmichaelo so I asked @jduckles and he discovered that names with special characters need to be enclosed in square brackets like this:

["Hans Gunnar Slokvik Lian", "Kyrre Traavik Låberg", "Dan Michael Olsen Heggø"]

or the `YAML` chokes. All fixed now - and it only took more than 30 minutes ;-)

Glad your workshop is finally listed !

**Comment by jduckles** [comment]
We actually want this to be the string: `"Hans Gunnar Slokvik Lian, Kyrre Traavik Låberg, Dan Michael Olsen Heggø"` (note there are no intermediate quotes).  I have PR'd that as a more sustainable fix.

**Comment by jduckles** [comment]
The list form with square brackets is probably a preferred long-term approach, but none of the other `who:` items use a list form, and the Jekyll templates these data feed to probably don't expect a list. In SWC/DC workshop web pages, the list form is used, so to be consistent I'd recommend moving to using lists of distinct instructor names rather than a string naming many people within it.

**Comment by danmichaelo** [comment]
Ouch, must have worked for too long yesterday. Thanks for fixing! Yes, an array would be more intuitive :)

**Pull request merged**
